name: 'xema_weather'
version: '1.0.0'
config-version: 2
profile: 'xema_weather'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  xema_weather:
    staging:
      +materialized: view
      stg_dim_variables:
        +tags: ['dimensions']
      stg_dim_stations:
        +tags: ['dimensions']
      stg_weather_data:
        +tags: ['observations']

    core:
      +materialized: incremental
      fct_weather_readings:
        +tags: ['facts', 'minute-level']
