xema_weather:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: catalonia-weather-data-xema
      dataset: xema_weather
      threads: 4
      keyfile: "{{ env_var('GCP_SA_KEY') }}"
      location: europe-southwest1
